---
stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.11"
  PYTHON_IMAGE: "python:${PYTHON_VERSION}"


.common:
  image: ${PYTHON_IMAGE}
  before_script:
    - pip install -r test_requirements.txt
    - pip freeze > test_requirements.freeze
    - python --version

python:
  extends: .common
  stage: lint
  script:
    - flake8 .

unittest:
  extends: .common
  stage: test
  script:
    - pytest tests
    - coverage run --source errata_server `which pytest` tests
    - coverage report
...
