name: Linting
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

        # test_requirements contains tools needed for flake8, etc.
      - name: Install requirements
        run: pip3 install -r test_requirements.txt
      - name: Run linting test
        run: flake8 .
